<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="ScriblySequenceBoot" Id="{941514a7-a423-4bd0-8245-a3a62112b594}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ScriblySequenceBoot EXTENDS ScriblySequence IMPLEMENTS ZCore.ISequence
VAR
  _step : ZCore.Step(ScriblyStep.BootBegin, ScriblyStep.BootEnd);
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[IF OnStart(_step) THEN
  ; // init custom sequence variables here ...
END_IF

REPEAT
  LogStep();

  CASE _step.Index OF
    (* -------------------------------------------------------------------------------------------------------------------------------- *)
    ScriblyStep.BootBegin:
    (* -------------------------------------------------------------------------------------------------------------------------------- *)
      IF _step.OnEntry()
      THEN
        // initialize equipment
        _io();
        _actuator();
        _fieldbus();
        _axis();
        _unit();
      END_IF
      
      _parent._objectManager.Cyclic();      
      Assert(_parent._objectManager);
      IF _parent._objectManager.Done
      THEN
        _step.SetNext(ScriblyStep.BootEnd);
      END_IF

    (* -------------------------------------------------------------------------------------------------------------------------------- *)
    ScriblyStep.BootEnd:
    (* -------------------------------------------------------------------------------------------------------------------------------- *)
      SetBusy(FALSE);
      
  ELSE
    Abort('sequence contains unhandled step');
  END_CASE
UNTIL _step.IsNotRepeatable() OR_ELSE NOT Busy END_REPEAT]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>
