<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="ScriblyEquipment" Id="{dda9199d-3b7f-4fd0-8bd1-38b9dc557fbe}" SpecialFunc="None">
    <Declaration><![CDATA[/// This function block is a container for equipment that is used by this unit.
/// Equipment is grouped by its kind (actuator, axes, io, ...).
/// It extends from [ManagedObjectContainer](xref:ZCore.ManagedObjectContainer) such that the parent
/// (= the unit itself) can be passed to equipment instances.
FUNCTION_BLOCK ScriblyEquipment EXTENDS ScriblyContainer
VAR_INPUT
  Io : ScriblyIo(_parent);
  Actuator : ScriblyActuator(_parent);
  Axis : ScriblyAxis(_parent);
  Fieldbus : ScriblyFieldbus(_parent);
  Unit : ScriblyLinkedUnit(_parent);
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>
